name: coisarapida
description: "Plataforma de entregas urbanas instantâneas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Estado e Arquitetura
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  # Navegação
  go_router: ^16.1.0

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^7.1.1
  firebase_app_check: ^0.4.0


  # Mapas e Localização
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # UI e Animações
  cupertino_icons: ^1.0.6
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0

  # Utilitários
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.5
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  uuid: ^4.2.1

  # Validação e Formatação
  mask_text_input_formatter: ^2.5.0
  validatorless: ^1.2.3
  flutter_custom_tabs: ^2.4.0
  cloud_functions: ^6.0.2
  app_links: ^6.4.1
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  riverpod_generator: ^3.0.0-dev.17
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Testes
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
