name: coisarapida
description: "Plataforma de entregas urbanas instantâneas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Estado e Arquitetura
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navegação
  go_router: ^12.1.3

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6

  # Mapas e Localização
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # UI e Animações
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Utilitários
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  uuid: ^4.2.1

  # Validação e Formatação
  mask_text_input_formatter: ^2.5.0
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Testes
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
